-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 18:07:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` INT NULL,
  `puerta` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  `codigoPostal` INT NULL,
  `pais` VARCHAR(45) NULL DEFAULT 'España',
  `telefono` VARCHAR(11) NULL,
  `fax` VARCHAR(11) NULL,
  `nif` VARCHAR(10) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marcas` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NULL,
  `Proveedores_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marcas_Proveedores_idx` (`Proveedores_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Marcas_Proveedores`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `mydb`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Monturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Monturas` (
  `idMontura` INT NOT NULL AUTO_INCREMENT,
  `montura` VARCHAR(45) NULL,
  PRIMARY KEY (`idMontura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cristales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cristales` (
  `idCristal` INT NOT NULL AUTO_INCREMENT,
  `cristal` VARCHAR(45) NULL,
  PRIMARY KEY (`idCristal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gafas` (
  `idGafa` INT NOT NULL AUTO_INCREMENT,
  `Marcas_idMarca` INT NOT NULL,
  `graduacion1` DECIMAL NULL,
  `graduacion2` DECIMAL NULL,
  `precio` DECIMAL NULL,
  `cristales` INT NULL,
  `Monturas_idMontura` INT NOT NULL,
  PRIMARY KEY (`idGafa`),
  INDEX `fk_Gafas_Marcas1_idx` (`Marcas_idMarca` ASC) VISIBLE,
  INDEX `fk_Gafas_Monturas1_idx` (`Monturas_idMontura` ASC) VISIBLE,
  INDEX `fk_Gafas_Cristales1_idx` (`cristales` ASC) VISIBLE,
  CONSTRAINT `fk_Gafas_Marcas1`
    FOREIGN KEY (`Marcas_idMarca`)
    REFERENCES `mydb`.`Marcas` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gafas_Monturas1`
    FOREIGN KEY (`Monturas_idMontura`)
    REFERENCES `mydb`.`Monturas` (`idMontura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gafas_Cristales1`
    FOREIGN KEY (`cristales`)
    REFERENCES `mydb`.`Cristales` (`idCristal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` INT NULL,
  `puerta` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  `codigoPostal` INT NULL,
  `pais` VARCHAR(45) NULL,
  `telefono` VARCHAR(11) NULL,
  `email` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `Cliente_idCliente` INT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `Gafas_idGafa` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Ventas_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Ventas_Gafas1_idx` (`Gafas_idGafa` ASC) VISIBLE,
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Gafas1`
    FOREIGN KEY (`Gafas_idGafa`)
    REFERENCES `mydb`.`Gafas` (`idGafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (`idVenta` INT, `nombre` INT, `Marca` INT, `precio` INT, `Vendido` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`GafasView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GafasView` (`idGafa` INT, `Marca` INT, `graduacion1` INT, `graduacion2` INT, `precio` INT, `cristal` INT, `montura` INT, `Proveedor` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`Marcas_Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marcas_Proveedores` (`idMarca` INT, `Marca` INT, `Proveedor` INT, `idProveedor` INT);

-- -----------------------------------------------------
-- View `mydb`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Factura`;
USE `mydb`;
CREATE  OR REPLACE VIEW `Factura` AS SELECT v.`idVenta`,c.`nombre`, g.`Marca`,g.`precio`,e.`nombre` AS `Vendido` FROM `Cliente` AS `c` INNER JOIN `Ventas`AS `v` ON v.`Cliente_idCliente`=c.`idcliente` INNER JOIN `GafasView` AS `g` ON g.`idGafa`=v.`Gafas_idGafa` INNER JOIN `Empleados`AS `e` ON v.`Empleados_idEmpleados`=e.`idEmpleados`;

-- -----------------------------------------------------
-- View `mydb`.`GafasView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GafasView`;
USE `mydb`;
CREATE  OR REPLACE VIEW `GafasView` AS SELECT g.`idGafa`,ma.`Marca`,g.`graduacion1`,g.`graduacion2`,g.`precio`,c.`cristal`,mo.`montura`,mp.`Proveedor` FROM `Gafas` AS `g` INNER JOIN `Cristales` AS `c` ON g.`cristales`=c.`idCristal` INNER JOIN `Monturas`AS `mo`ON g.`Monturas_idMontura`=mo.`idMontura` INNER JOIN `Marcas` AS `ma` ON g.`Marcas_idMarca`=ma.`idMarca` INNER JOIN `Marcas_Proveedores` AS `mp` ON mp.`idMarca`=g.`Marcas_idMarca`;

-- -----------------------------------------------------
-- View `mydb`.`Marcas_Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Marcas_Proveedores`;
USE `mydb`;
CREATE  OR REPLACE VIEW `Marcas_Proveedores` AS SELECT m.`idMarca`,m.`Marca`, p.`nombre`  AS `Proveedor`,p.`idProveedor` FROM `Marcas` AS `m` INNER JOIN `Proveedores` AS `p` ON m.`Proveedores_idProveedor`=p.`idProveedor`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
